<?php

return [
    //======================================================== for requester is not accounting team ==========================
    //======== flow within budget amount <=5000usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'Y',
        'amount_request'   => '<=10000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '2',
        'checker'          => 'accounting',
        'within_budget'    => 'Y',
        'amount_request'   => '<=10000',
        'step_description' => 'accounting',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '3',
        'checker'          => 'approver',
        'within_budget'    => 'Y',
        'amount_request'   => '<=10000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '4',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'Y',
        'amount_request'   => '<=10000',
        'step_description' => 'accounting',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],
    //======== flow within budget amount <=10000usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'Y',
        'amount_request'   => '<=50000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '2',
        'checker'          => 'accounting',
        'within_budget'    => 'Y',
        'amount_request'   => '<=50000',
        'step_description' => 'accounting',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '3',
        'checker'          => 'approver',
        'within_budget'    => 'Y',
        'amount_request'   => '<=50000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '4',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'Y',
        'amount_request'   => '<=50000',
        'step_description' => 'accounting and finance',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],

    //======== flow within budget amount >10000 usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '2',
        'checker'          => 'accounting',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'accounting',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '3',
        'checker'          => 'md_office',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'md_office',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '4',
        'checker'          => 'approver_ceo',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'approver_ceo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '5',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'accounting_finance',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],

     //======== flow notwithin budget amount <=5000usd ====================
     [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '2',
        'checker'          => 'accounting',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'accounting',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '3',
        'checker'          => 'approver',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '4',
        'checker'          => 'approver_cfo',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'approver_cfo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '5',
        'checker'          => 'md_office',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'md_office',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '6',
        'checker'          => 'approver_ceo',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'approver_ceo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '7',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'accounting_finance',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],

    //======== flow notwithin budget amount <=10000usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '2',
        'checker'          => 'accounting',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'accounting',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '3',
        'checker'          => 'approver',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '4',
        'checker'          => 'approver_cfo',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'approver_cfo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '5',
        'checker'          => 'md_office',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'md_office',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '6',
        'checker'          => 'approver_ceo',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'approver_ceo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '7',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'accounting_finance',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],

    //======== flow notwithin budget amount >10000usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '2',
        'checker'          => 'accounting',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'accounting',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '3',
        'checker'          => 'approver_cfo',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'approver_cfo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '4',
        'checker'          => 'md_office',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'md_office',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '5',
        'checker'          => 'approver_ceo',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'approver_ceo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],[
        'step_number'      => '6',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'accounting_finance',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 0,
    ],

    //======================================================== for requester is accounting team ==========================
    //======== flow within budget amount <=5000usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'Y',
        'amount_request'   => '<=10000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '2',
        'checker'          => 'approver',
        'within_budget'    => 'Y',
        'amount_request'   => '<=10000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],
    [
        'step_number'      => '3',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'Y',
        'amount_request'   => '<=10000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],

    //======== flow within budget amount <=10000usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'Y',
        'amount_request'   => '<=50000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '2',
        'checker'          => 'approver',
        'within_budget'    => 'Y',
        'amount_request'   => '<=50000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '3',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'Y',
        'amount_request'   => '<=50000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 0,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],

    //======== flow within budget amount >10000 usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '2',
        'checker'          => 'md_office',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'md_office',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '3',
        'checker'          => 'approver_ceo',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'approver_ceo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '4',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'Y',
        'amount_request'   => '>50000',
        'step_description' => 'accounting_finance',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],

     //======== flow notwithin budget amount <=5000usd ====================
     [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '2',
        'checker'          => 'approver',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '3',
        'checker'          => 'approver_cfo',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'approver_cfo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '4',
        'checker'          => 'md_office',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'md_office',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '5',
        'checker'          => 'approver_ceo',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'approver_ceo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '6',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'N',
        'amount_request'   => '<=10000',
        'step_description' => 'accounting_finance',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],

    //======== flow notwithin budget amount <=10000usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '2',
        'checker'          => 'approver',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'Second line of Exco A1,A2,A3...',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '3',
        'checker'          => 'approver_cfo',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'approver_cfo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '4',
        'checker'          => 'md_office',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'md_office',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '5',
        'checker'          => 'approver_ceo',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'approver_ceo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '6',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'N',
        'amount_request'   => '<=50000',
        'step_description' => 'accounting_finance',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],

    //======== flow notwithin budget amount >10000usd ====================
    [
        'step_number'      => '1',
        'checker'          => 'first_reviewer',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'first reviewer',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '2',
        'checker'          => 'approver_cfo',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'approver_cfo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '3',
        'checker'          => 'md_office',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'md_office',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '4',
        'checker'          => 'approver_ceo',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'approver_ceo',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],[
        'step_number'      => '5',
        'checker'          => 'accounting_finance',
        'within_budget'    => 'N',
        'amount_request'   => '>50000',
        'step_description' => 'accounting_finance',
        'version'          => 2,
        'approver_is_ceo'  => 1,
        'req_name'         => '3',
        'notification_type'=>'AdvanceFormRequest',
        'is_accounting_team' => 1,
    ],
];
